let questions = [
    {   "question_img" : "img/img1.jpg",
        "question" : "Um welches bekannte Spiel handelt es sich",
        "answers" : ["Mühle","Schach","Mensch ärgere dich nicht","Monopoly"],
        "player_answer": 99,
        "right_answer" : 1,     // 0-3
        "category" : "Brettspiele",
    },
    {   "question_img" : "img/img2.jpg",
        "question" : "Wieviele Spieler stehen bei einem normalen Fußballspiel auf dem Spielfeld",
        "answers" : ["11","20","22","14"],
        "player_answer": 99,
        "right_answer" : 2,     // 0-3
        "category" : "Sport",
    },
    {   "question_img" : "img/gamesImg.jpg",
        "question" : "Wieviele Champions bilden in 'League of Legends' ein Team",
        "answers" : ["10","2","Es ist ein Single-Player-Spiel","5"],
        "player_answer": 99,
        "right_answer" : 3,     // 0-3
        "category" : "Videospiele",
    },
    {   "question_img" : "img/img4.jpg",
        "question" : "Aus welchem Spiel stammt das angezeigte Bild",
        "answers" : ["Minecraft","Call of Duty","Civilisation","Super Mario"],
        "player_answer": 99,
        "right_answer" : 0,     // 0-3
        "category" : "Videospiele",
    },
    {   "question_img" : "img/img5.jpg",
        "question" : "In welchem Jahr erschien die PlayStation 1 in Japan",
        "answers" : ["1993","1994","1992","1991"],
        "player_answer": 99,
        "right_answer" : 1,     // 0-3
        "category" : "Videospiele",
    },
    {   "question_img" : "img/img6.jpg",
        "question" : "Welches bekannte Unternehmen entwickelte die XBox",
        "answers" : ["Microsoft","Sony","Nintendo","Reinmetall"],
        "player_answer": 99,
        "right_answer" : 0,     // 0-3
        "category" : "Videospiele",
    },
    {   "question_img" : "img/gamesImg.jpg",
        "question" : "Wie heißt der Hauptprotagonist aus 'The Legend of Zelda'",
        "answers" : ["Yoshi","Zelda","Mario","Link"],
        "player_answer": 99,
        "right_answer" : 3,     // 0-3
        "category" : "Videospiele",
    },
    // {   "question_img" : "img/gamesImg.jpg",
    //     "question" : "Um welches bekannte Spiel handelt es sich",
    //     "answers" : {
    //         1 : "Mühle",
    //         2 : "Schach",
    //         3 : "Mensch ärgere dich nicht",
    //         4 : "Monopoly"
    //     },
    //     "right_answer" : 2,
    // },
];